### ISSUE TITLE
installation errors on tkinter

### ISSUE THREAD

**Issue by aslangabriel** [SysBioUAB/PyAMPA#1]
hi, I tried to run your app on WSL2 linux subsytem. There is no python3.11 available on the minisystem. I installed it manually and succeeded, while the error still occurred after running python3 main.py. The message was as follows"root@DESKTOP-M6BE6MT:/home/aslanganriel/PyAMPA# python3 main.py 
No protocol specified
No protocol specified
Traceback (most recent call last):
  File "main.py", line 1090, in <module>
    app = Application()
  File "main.py", line 705, in __init__
    tk.Tk.__init__(self)
  File "/usr/lib/python3.8/tkinter/__init__.py", line 2270, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: couldn't connect to display ":21.0"
root@DESKTOP-M6BE6MT:/home/aslanganriel/PyAMPA# python3.11 main.py 
Traceback (most recent call last):
  File "/home/aslanganriel/PyAMPA/main.py", line 1, in <module>
    import tkinter as tk
  File "/usr/local/lib/python3.11/tkinter/__init__.py", line 38, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
    ^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named '_tkinter'
". Would you like to fix it? I appreciate it very much.

**Comment by SysBioUAB** [comment]
We did not test the software on WSL2 linux subsytem, pyAMPA is intended for use in a native linux environment (or mac). Did you try to install tkinter? { ModuleNotFoundError: No module named '_tkinter' } suggests that tkinter is not properly installed in your system. You can try to install tkinter to solve this issue:

`sudo apt install python3-tk`

This error { _tkinter.TclError: couldn't connect to display ":21.0" } suggests also that you're trying to execute tkinter in an environment with no graphical display available. Tkinter requires access to a display in order to function properly.

Please let us know if this helped to solve your problems.

Best regards,

The pyAMPA Team
